theme: jekyll-theme-minimal

title: Mutable Type 
description: A repository of poetry in progress.

defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      page.history_path: "/commits/master/_posts/"
